### ISSUE TITLE
The APIs are no longer rendered in the spec

### ISSUE THREAD

**Issue by brianorwhatever** [w3c-ccg/vc-api#341] opened 2023-03-27 18:19 UTC
I believe the APIs were previously being presented in the proper sections of the specification however they are now blank.. Did something happen to remove them?

See https://w3c-ccg.github.io/vc-api/#issuing

**Comment by jrhender** [comment] 2023-04-20 08:55
@msporny I believe that the change that caused this issue was this commit https://github.com/w3c-ccg/vc-api/commit/04486fbed58cc5acc87c1571ee376d6d2c848212
I believe that the issue is that `scheme: signature` is not being parsed as a valid `scheme` for OpenAPI. This analysis is from my local building and testing of the spec.

If this is indeed the issue, I'm not sure what the best way to fix this would be. Is `scheme: bearer` not right for `zCap`?

**Comment by msporny** [comment] 2023-04-20 13:18
> @msporny I believe that the change that caused this issue was this commit [04486fb](https://github.com/w3c-ccg/vc-api/commit/04486fbed58cc5acc87c1571ee376d6d2c848212) I believe that the issue is that `scheme: signature` is not being parsed as a valid `scheme` for OpenAPI. This analysis is from my local building and testing of the spec.

Yes, you are correct. I've re-created the issue locally as well.

The problem is that the definition is valid against the OAS spec, but invalid against the OAS schema file. You're supposed to be able to use any scheme that's registered in the HTTP Authentication Scheme Registry:

https://swagger.io/docs/specification/authentication/

... but looks like whoever put the JSON Schema together didn't do that:

https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.json#L1328

... which results in the schema validation check failing.

> If this is indeed the issue, I'm not sure what the best way to fix this would be. Is `scheme: bearer` not right for `zCap`?

Yes, 'zcaps' are not bearer tokens... you have to digitally sign each invocation. You could argue that once the signature is performed, that it's a bearer token for a very limited window of time... BUT, it's certainly not a bearer token in the sense that OAuth2 uses bearer tokens. The scheme *is* `Signature` -- but it turns out that the OAS schema will reject that (AFAICT).

In any case, I hacked something temporarily so the spec will generate again here:

https://github.com/w3c-ccg/vc-api/commit/c97ad7e55b2955fa6d7c9da9bcffe6130589d587

Closing as fixed.

**Closed by msporny** 2023-04-20 13:18 UTC
