### ISSUE TITLE
Intro/discussion of VC-HTTP-API to the CCG

### ISSUE THREAD

**Issue by vsnt** [w3c-ccg/vc-api#172] opened 2021-03-23 14:52 UTC
Concerns have been brought up that there needs more clarity on this repo & what it does to people not involved in the SVIP cohort. It has also been suggested that problem/solutions be discussed in the context of the CCG: https://github.com/w3c-ccg/vc-http-api/pull/168#issuecomment-803635860. To solve these, I would like to propose the following:

An intro to the VC-HTTP-API session, which is an intro + background of this work, the application & examples to the CCG main call. After the intro, identify existing problem concerns that should be discussed in the CCG w/ more generalized CCG participation.

Thoughts? @mprorock @OR13 @msporny @antiltj @bumblefudge @kimdhamilton

**Comment by mprorock** [comment] 2021-03-23 14:54
Big fan of an intro call on this topic and will happily support

**Comment by bumblefudge** [comment] 2021-03-23 15:51
I'll be there!  How much time are we talking?

**Comment by aniltj** [comment] 2021-03-24 13:02
Very much support having this discussion at the W3C/CCG!

Background (from my Perspective)
-----
A major concern that any Enterprise has (including DHS), based on painful experiences in the past, is vendors locking us into proprietary/licensed APIs for their solutions/platforms that increased the cost of moving away from them to be so high, that we ended being captured by them unless we were willing to incur that cost.

So, when the original DHS/SVIP solicitation went out back in the day seeking talent to solve both our Virtual Credential and Supply Chain Traceability work, we had some specific language in that solicitation that would mitigate this type of vendor lock-in in the future, that ALL companies that we fund under this solicitation would need to support:

"All APIs that are presented to the Issuer and the Verifier SHALL be publicly documented, patent free, royalty free, non-discriminatory, available to all, and free to implement using widely available and supported programming languages"

During our work kick-off meeting we also sat down with the vendors and articulated the following:

- We are NOT going to tell you what this API should be, beyond what we already articulated as intent
- We are not going to share our internal API with you, as you building to that  would make this solution inherently government focused - and that was not something that we want in any shape or form.
- We want you to come up with an API that supports the broader ecosystem that we can also support as an active participant in that ecosystem
- We believe that this approach is useful not just to DHS but to the broader ecosystem, so what we expect you to do is work together in public at the W3C/CCG to jointly develop this API with the ability to consult with and take input from the global technical community, so that it is useful not just to DHS but also useful to the broader ecosystem
- We expect you to come to us with *ONE* API that you (vendors under contract) can agree with, that incorporates the global technical community perspective and we, provided we understand the full implications of what is being proposed and it aligns with our Enterprise, will support that API for how we integrate with you.
- You are free to build value added services / "magic sauce" on top of / behind this open API but we will not support any mechanism that is by design set up to lock us into a proprietary vendor solution. We want that common, interoperable baseline across multiple vendor implementations - which is the articulated intent of this API

What Happened
---

- The answer to our need and question by the SVIP cohort companies has been the VC-HTTP-API
- There has also been an extensive test suite built around this that we use to ensure that the API is implemented in a manner by all of them that enables truly interoperable operations across the diverse set of vendors we have under contract.
- Given the differences in use cases between our Virtual Credential work (person as holder) and the Supply Chain Traceability work (organization as holder) different companies in the cohort have different needs/perspectives on which particular pieces of the API applies to them and support << that conversation continues!

**Comment by msporny** [comment] 2022-02-13 22:57
This happened on 2021-04-20 (unfortunately, the minutes seem to not be published for that meeting... but we do have the raw audio and IRC logs on the server).

Closing since this happened.

CCG Chairs will have to figure out what happened to the minutes. Raw logs here:

https://meet.w3c-ccg.org/archives/w3c-ccg-weekly-2021-04-20-irc.log

**Closed by msporny** 2022-02-13 22:57 UTC
